# Generated by Django 2.0.4 on 2018-05-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='text_about',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
    ]
