# Generated by Django 2.0.4 on 2018-05-23 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keywords', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.TextField(verbose_name='Название работы')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на работу на сайте источника')),
                ('author', models.TextField(verbose_name='Автор работы')),
                ('abstract', models.TextField(blank=True, verbose_name='Аннотация')),
                ('keywords', models.ManyToManyField(to='keywords.KeyWord', verbose_name='Ключевые слова')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Научные статьи',
                'verbose_name': 'Научная статья',
            },
        ),
    ]
