# Generated by Django 2.0.3 on 2018-03-28 23:51

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.TextField(verbose_name='Название работы')),
                ('url', models.URLField(verbose_name='Ссылка на работу на сайте источника')),
                ('author', models.TextField(verbose_name='Автор работы')),
            ],
            options={
                'verbose_name': 'Научная статья',
                'verbose_name_plural': 'Научные статьи',
            },
        ),
    ]
