# Generated by Django 2.0.4 on 2018-05-25 18:50

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('file', models.FileField(upload_to='attachment', verbose_name='Файл')),
                ('to_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='papers.ResearchPaper', verbose_name='Научная работа')),
            ],
            options={
                'verbose_name': 'Вложение научной работы',
                'verbose_name_plural': 'Вложения научной работы',
            },
        ),
    ]
